### ISSUE TITLE
Setup website to support mobile app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#1]
Setup dev, test, live websites on Pantheon

www.european-mammals.brc.ac.uk

**Comment by BirenRathod** [comment]
@DavidRoy 

1. Dev environment of european mammal is ready to play around. URL is http://dev-european-mammals.pantheonsite.io/
2. username and password are stored in the keypass
3. I added John username on Pantheon, so he will receive the details.

**Comment by johnvanbreda** [comment]
@BirenRathod presumably this site should have a Bootstrap base theme applied? Is this something you can do?
Thanks.

**Comment by BirenRathod** [comment]
@johnvanbreda 
yes, I can do that. Have you got any particular color scheme in mind? let me know.

**Comment by DavidRoy** [comment]
https://mammalnet.tuinbit.com/mammalx

Is the main website for the project, so we should follow the colour scheme there.  The Indicia site is for managing users and for reports

**Comment by BirenRathod** [comment]
Thanks, @DavidRoy.
I will keep the same for this too.

**Comment by DavidRoy** [comment]
@BirenRathod next steps are:
1. match colour scheme of https://european-mammals.brc.ac.uk to https://mammalnet.tuinbit.com/mammalx/
2. Add in this logo to the page header banner
[logo.zip.zip](https://github.com/BiologicalRecordsCentre/MammalNet-Europe/files/3661723/logo.zip.zip)
3. Create page footer (similar to butterfly-monitoring.net
Copyright © 2019 Centre for Ecology & Hydrology.
Privacy Notice

**Comment by BirenRathod** [comment]
@DavidRoy & @johnvanbreda  
 Thanks for the logo although I have downloded from mammalnet site.
1. I have added the bootstrap theme with matching color.
2. Logo have been added.
3. Page footer create and link for CEH & privacy notice have been added. There is no privacy notice page yet which needs be create.

Although, I have added theme there are still require some implementation for better display of Indicia reports which can be done in due course.

It is on dev site at present.

**Comment by DavidRoy** [comment]
@BirenRathod There is a different logo for the app, which was in the .zip file above.

Please can you apply the styling and footer to the live site.  The live site has the privacy notice page (https://european-mammals.brc.ac.uk/privacy-notice) and some home page text that need to be retained.

**Comment by BirenRathod** [comment]
@DavidRoy & @johnvanbreda 
Just in case if you haven't seen, the styling has been done now for the site. New logo & icon has been created. Also, SMTP email has been setup.

**Comment by DavidRoy** [comment]
Thanks.  Looks good.
