### ISSUE TITLE
record-details link from explore my-records broken

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#12]
The record details link from:
https://european-mammals.brc.ac.uk/explore/my-records

is broken.  It points to:
https://european-mammals.brc.ac.uk/record-details?occurrence_id=11928486

The record details link from explore all records:
https://european-mammals.brc.ac.uk/explore/all-records

does work:
https://european-mammals.brc.ac.uk/details/record?occurrence_id=11928486

**Comment by johnvanbreda** [comment]
Fixed.

**Comment by DavidRoy** [comment]
Thanks
