### ISSUE TITLE
ElasticSearch overall summary report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#13]
To show progress with data submitted, we require reports on activity.  Start simple with a table (based on https://butterfly-monitoring.net/elastic/summary-by-country-year?) of:

Country
Number of records
Number of recorders
Number of species

**Comment by johnvanbreda** [comment]
Done - https://european-mammals.brc.ac.uk/elastic/summary-by-country-year
