### ISSUE TITLE
verification error message

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#15]
When verifying a record via https://european-mammals.brc.ac.uk/verify

Error message box appears with 'Elasticsearch update failed' with an OK button to continue.  However, the record verification works, see: https://european-mammals.brc.ac.uk/record/details?occurrence_id=11968594

![ver es](https://user-images.githubusercontent.com/2699478/67019112-0ea6a700-f0f4-11e9-89f7-280f6cafd2f3.png)

**Comment by johnvanbreda** [comment]
Fixed - please close if OK.
