### ISSUE TITLE
Improved record deletion message

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#16]
Currently, the record deletion button says 'Delete list of records'.  This may concern recorders as to what will be deleted.  The iMammalia app only submits single-occurrence samples so the button can be relabelled as 'Delete record'

The message to confirm deletion should make clear that there will be a lag in the explore-my records page due to ElasticSearch indexing?

**Comment by johnvanbreda** [comment]
I've changed the button by limiting the form to single record mode. Also added a message to the page (which is the same solution as on ABLE).
