### ISSUE TITLE
Verification page - additional filters

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#17]
For https://european-mammals.brc.ac.uk/verify

The current filter only allows own record filtering.

Need to add Status filer options as available on iRecord: https://www.brc.ac.uk/irecord/elastic/verification

e.g. pending, accepted, queried etc...

**Comment by johnvanbreda** [comment]
Done - please close if OK.

**Comment by DavidRoy** [comment]
thanks!
