### ISSUE TITLE
Link to Polish translation of privacy notice

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#18]
We have multi-lingual support on https://european-mammals.brc.ac.uk.

A translated version of the privacy notice is available in Polish (https://european-mammals.brc.ac.uk/pl/privacy-notice)

The link to the privacy notice is in the page footer.  When selecting Polish as the language, this link should change to point to the Polish version

**Comment by BirenRathod** [comment]
@DavidRoy 
The privacy link is setup in the footer block, so you need to translate block into that language (e.g. polish), once you create that block, amend the link according to language. I done for Polish but you can do that to other languages too.
