### ISSUE TITLE
Wild boar given incorrect family in ES report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#19]
https://european-mammals.brc.ac.uk/records/explore/all

Sus scrofa is given Family = Ursidae

Should be Family = Suidae

In Taxon list = 258 the higher taxonomy is right.  Is the issue coming from links to UKSI higher taxonomy ?

**Comment by johnvanbreda** [comment]
I've fixed the incorrect family name in the lookup data used by Elasticsearch. I have no idea why it was incorrect in the first place though as everything looks correct. Please close if OK (I don't have rights).

**Comment by DavidRoy** [comment]
Thanks
