### ISSUE TITLE
add ES my-records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#2]
To enable users to view/edit their app submissions

www.european-mammals.brc.ac.uk/my-records

**Comment by johnvanbreda** [comment]
Basic my records report added to site (though of course there are no records to view yet).

**Comment by DavidRoy** [comment]
page gives error pop-up (Elasticsearch query failed)

**Comment by johnvanbreda** [comment]
Are you logged in when you get this error? Which version of the site?

**Comment by DavidRoy** [comment]
When logged in as admin.

Also when logged out - the page should not be available when logged out

**Comment by johnvanbreda** [comment]
Fixed - rebuilt content permissions.
