### ISSUE TITLE
Options to minimise emails being treated as Spam

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#21]
Emails to verify accounts seem to be getting caught by email spam filters - presumably because they contain links.  Are there options to minimise this?

**Comment by DavidRoy** [comment]
@BirenRathod is this now resolved, and can we close the issue?

**Comment by BirenRathod** [comment]
@DavidRoy 
How to find about it? if this is working or not.

**Comment by DavidRoy** [comment]
@BirenRathod there are still a lot of non-activated accounts which I think means the problem remains.  Are there any setting to minimise the likelihood of getting caught by spam filters?

**Comment by BirenRathod** [comment]
@DavidRoy 
Ok, thanks. I will investigate about it and let you soon.

**Comment by BirenRathod** [comment]
@DavidRoy 
I have now enabled Captcha module. To register/login, user have to go through Captcha root. 
Also, there is a provision of restriction user in https://european-mammals.brc.ac.uk/admin/config/people/user-restrictions. So if you see any suspicious account, you can add rule into this which should prevent to create a spam account.

**Comment by DavidRoy** [comment]
@BirenRathod Thanks but I don't think these are all the steps to solve the issue.  Most registrations are through the app but when users receive an email to verify their account, this email is getting caught in Spam filters so users never fully activate their accounts - i.e. because the email contains links and is not from a trusted source?

**Comment by BirenRathod** [comment]
@DavidRoy 
The website sends email from imammalia@ceh.ac.uk. and spam filter works thorough third party of this https://aws.amazon.com/ses/. If only this website experience this problem, there may be a possibility that rule setup to restricts account created outside UK.

**Comment by BirenRathod** [comment]
@DavidRoy 
Which user has been blocked? is it this miulerux@gmail.com? is there any other?

**Comment by BirenRathod** [comment]
@DavidRoy 
One suggestion could help. can we keep only one address imammalia@ceh.ac.uk on the site? at present email sends from brc@ceh.ac.uk with reply-to imammalia@ceh.ac.uk.

**Comment by DavidRoy** [comment]
@BirenRathod  I unblocked about 20 users this morning.  Yes, setting the email address to imammalia@ceh.ac.uk sounds like a good option

**Comment by johnvanbreda** [comment]
The site runs from the domain brc.ac.uk though doesn't it? Therefore the email should be from the same domain to avoid being treated as spam.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Both emails have got same domain but to not give confusion to spam filter system, it is good idea to keep one email address as a sender and for site itself. I just changed it to imammalia@ceh.ac.uk

**Comment by johnvanbreda** [comment]
No, it's not that the emails need the same domain as each other, it's that the emails need the same domain as the site isn't it? Since the site runs from *.brc.ac.uk and the emails are from *.ceh.ac.uk they are likely to be blocked as spam.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Domain is not a problem. we just tested two registrations using two emails from website (not from app), and it works fine. no problem.

**Comment by DavidRoy** [comment]
Thanks for your inputs and testing.  It's hard to test this given differences in email servers and we don't know whether non-activations are because of missed emails due to Spam filters or users just not completing the process.  I suggest we close this issue for now, but revisit if it becomes an issue reported by users

**Comment by johnvanbreda** [comment]
@BirenRathod I disagree. Just because a registration email arrives for one person without spam filtering does not mean that another person will not have problems due to different spam filtering. In your case, if the test was from a ceh registered email address, it makes sense that the spam filtering might be different to someone elsewhere. 

The point is that if an email is sent from domain a but has the "from" header set to domain b, then this is often interpreted as impersonation, so the email is more likely to be considered spam. In this case, the email is from *.brc.ac.uk but has the "from" header set to *.ceh.ac.uk.

**Comment by BirenRathod** [comment]
@johnvanbreda 
That is why we (another person from CEH helpdesk) tried with three different emails non CEH one. Two registered from websites and one from app and all three works fine.

@DavidRoy 
About users just not completing process, we found that registering from the app which is slightly different to the website that users have to enter a name if they don't then they don't get error message, but the registration just doesn't work and stays on the page with no clue what's preventing you from registering.

I'm not suggesting this could be the reason of spam, but just might need may be implementation.

**Comment by BirenRathod** [comment]
@DavidRoy 
Further to this, I found, out of three accounts, only registered via app has been blocked. So there may be some problem registering users via app. Although email didn't end up in the spam. Something else, may be user status hasn't changed as active registering via app.

**Comment by DavidRoy** [comment]
Thanks.  I'll discuss with Karolis about the app registration
