### ISSUE TITLE
Corrections to mammal names and taxonomy

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#26]
Corrections needed to Mammal list (id=258).  Changes need to propagate through to ElasticSearch

CLASSIFICATION
Wild boar - Ursidae > Suidae
Brown bear - Procyonidae > Ursidae
Artiodactyla > Cetartiodactyla

SPELLING
Ericnaceomorpha  > Erinaceomorpha
Leporiadae  > Leporidae
Chamois, Alpine > Alpine Chamois or Northern Chamois

**Comment by johnvanbreda** [comment]
These name changes are done, please close if OK.

**Comment by DavidRoy** [comment]
Thanks
