### ISSUE TITLE
tracks and feaces / iMammalia App

### ISSUE THREAD

**Issue by okeuling** [BiologicalRecordsCentre/MammalNet-Europe#27]
It would be handy to offer images of tracks and faeces or other signs that suggest the presence of the species. Additionally, it would be interesting to have an interactive map that displays the entries of each member and/or each species (maybe sorted with the use of a filter)

**Comment by DavidRoy** [comment]
Do you mean example images of tracks and signs?  I agree that would be useful

The iMammalia website shows all the records and can be filtered.  Depending on resources, we may consider adding some mapping of records into the app

**Comment by okeuling** [comment]
This idea came from my students, I will have to ask, they are out in the field!

I guess, they did mean examples.

 

Best

Olli

 

 

---------------------------------

Dr. Oliver Keuling

Institut für Terrestrische und Aquatische Wildtierforschung · Stiftung Tierärztliche Hochschule Hannover · 

Institute for Terrestrial and Aquatic Wildlife Research · University of Veterinary Medicine Hannover ·

Bischofsholer Damm 15 · 30173 Hannover · Fon +49 511 856 7396 · Fax +49 511 856 827396 ·  <http://www.tiho-hannover.de/itaw> http://www.tiho-hannover.de/itaw 

 

Von: David Roy (CEH) <notifications@github.com> 
Gesendet: Freitag, 1. November 2019 14:44
An: BiologicalRecordsCentre/MammalNet-Europe <MammalNet-Europe@noreply.github.com>
Cc: Keuling, Oliver <Oliver.Keuling@tiho-hannover.de>; Author <author@noreply.github.com>
Betreff: Re: [BiologicalRecordsCentre/MammalNet-Europe] tracks and feaces / iMammalia App (#27)

 

Do you mean example images of tracks and signs? I agree that would be useful

The iMammalia website shows all the records and can be filtered. Depending on resources, we may consider adding some mapping of records into the app

**Comment by DavidRoy** [comment]
@okeuling are you able to confirm this requirement? thanks

**Comment by okeuling** [comment]
Hi David,

I do not get, what I am supposed to do?

Best

Olli

 

 

---------------------------------

Dr. Oliver Keuling

Institut für Terrestrische und Aquatische Wildtierforschung · Stiftung Tierärztliche Hochschule Hannover · 

Institute for Terrestrial and Aquatic Wildlife Research · University of Veterinary Medicine Hannover ·

Bischofsholer Damm 15 · 30173 Hannover · Fon +49 511 856 7396 · Fax +49 511 856 827396 · 

 

Von: David Roy (CEH) <notifications@github.com> 
Gesendet: Dienstag, 28. Januar 2020 15:20
An: BiologicalRecordsCentre/MammalNet-Europe <MammalNet-Europe@noreply.github.com>
Cc: Keuling, Oliver <Oliver.Keuling@tiho-hannover.de>; Mention <mention@noreply.github.com>
Betreff: Re: [BiologicalRecordsCentre/MammalNet-Europe] tracks and feaces / iMammalia App (#27)

 

@okeuling <https://github.com/okeuling>  are you able to confirm this requirement? thanks

**Comment by DavidRoy** [comment]
Confirm what the requirement is from your Github issue you raised:
https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues/27

i think there are two things you want:
1. Some additional images for the species guide to show examples of tracks/signs
2. A map of existing records within the mobile app.  A filterable report on records already exists on the website at https://european-mammals.brc.ac.uk/records/explore/all

If you can clarify the requirement(s), we can then look into how much work it is to implement

**Comment by okeuling** [comment]
1. correct!
2. that´s what the students are thinking about. you use the app in the field, you do not use the web-app afterwards. Thus, you do not see the map! For the users it would be great to see where to go to fill the gaps!
Olli

**Comment by okeuling** [comment]
1. correct!
2. that´s what the students are thinking about. you use the app in the field, you do not use the web-app afterwards. Thus, you do not see the map! For the users it would be great to see where to go to fill the gaps!
Olli

**Comment by okeuling** [comment]
1. correct!
2. that´s what the students are thinking about. you use the app in the field, you do not use the web-app afterwards. Thus, you do not see the map! For the users it would be great to see where to go to fill the gaps!
Olli
