### ISSUE TITLE
Seletion box misplaced 

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#28]
![imagen](https://user-images.githubusercontent.com/56724741/68129346-ac360f00-ff19-11e9-99a3-97bfdc56c6cd.png)
In Record detail form, selection box of the option sensitive species is misplaced (see image). 
This misplacing is happening also in other sections of the web using selection box

**Comment by johnvanbreda** [comment]
Done - please close if OK.

**Comment by JotablancoA** [comment]
thanks
