### ISSUE TITLE
add ES all-records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#3]
ElasticSearch report for all records submitted via the mobile app

www.european-mammals.brc.ac.uk\all-records

**Comment by johnvanbreda** [comment]
Basic all records report added to site (though of course there are no records to view yet).

**Comment by DavidRoy** [comment]
@johnvanbreda sorry John but I accidentally deleted this when trying to setup a home page on the site.
Can you reinstate the all-records explore report and add a separate home page to the site

**Comment by johnvanbreda** [comment]
I've re-instated all records.

The live site already has a page called Home so I've set that as the home page. It is just a basic page but we can replace it or add blocks using layout builder when the content required is known.

**Comment by DavidRoy** [comment]
Thanks, closing for now.  Will raise separate issues as required.
