### ISSUE TITLE
 Scientific names limitations and editions 

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#30]
1) Could be Included all the scientific names of European mammals in the species list in imammalia web?. If someone is certain that they have seen a specific species that is not in the app, they must be able to indicate/ edit it on the web. I understand the limitations of the app,  but in the web  it should be possible to edit species that do not appear in the app. It should no be complicate to increase the potential species list. Somebody sent European vison and users can not update the scientific name in the web. 
2) When I try to modify the species name in the edition section. I don get to save it. I receive error message; “The taxon must be specified”. Even if I introduce the same species names than previously I reported using the app. Could you verify if i am right or it was a temporary error?

**Comment by DavidRoy** [comment]
@JotablancoA 
1. yes, we can extend the species list.  Please provide a list of extra names to add.  We need to use a controlled list rather than users enter names
2. please can you let us know which ID you were trying to edit and the name to change to.  We can then investigate and fix if we replicate the bug

**Comment by DavidRoy** [comment]
@johnvanbreda to provide an export of current iMammalia species list.  To then be extended

**Comment by johnvanbreda** [comment]
List attached.

[european-mammals-list.txt](https://github.com/BiologicalRecordsCentre/MammalNet-Europe/files/4152384/european-mammals-list.txt)

**Comment by GrahamCSmith** [comment]
I think this is now working, as I can edit a species to be anything (i.e. not listed within the app). so this can be closed?
