### ISSUE TITLE
Store some records drafts in the app

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#31]
In the app, would it be possible for you to accumulate several records without sending and do it at another time? This would allow you to make more secure identifications, as it would allow you to perform self-checks before to send it.

**Comment by DavidRoy** [comment]
@kazlauskis is requirement here to have a 'submit all' option?

**Comment by kazlauskis** [comment]
At the moment, clicking the 'Finish' button within a record edit page will upload the record to the warehouse. This asks for an intermediate step to review the record when back at home before uploading it.

**Comment by kazlauskis** [comment]
This is done now.
