### ISSUE TITLE
Imagens for unknown species

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#32]
Some begginers users reported that are not confident with some scientific terminology. E.g. better to say rabbits or hares than lagomorph. Also I think It is easier for them to report unknown species if they have an image or silhouette. Many users are not clear what we mean by shrew, lagomorph, moles or voles. Some silhouettes image could be used to help them to send unknown species and increase their participation.

**Comment by DavidRoy** [comment]
@kazlauskis to confirm if this is an app-only requirement or need changes on the iMammalia website or indicia warehouse

**Comment by kazlauskis** [comment]
It is both, the app has to change the lagomorph to `Rabbits and Hares` which should also be translated to other languages. The website/warehouse should update the taxon:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/440891

**Comment by DavidRoy** [comment]
I've updated the warehouse taxon to add a common name for Lagomorph as 'Rabbits and Hares'.  This is the logical way to do this.
taxa_taxon_list_id = 441010
taxon_meaning_id = 195475
taxon_id = 385391

Does that give you enough information to update this in the app @kazlauskis

**Comment by kazlauskis** [comment]
Yes, this looks good. Cheers

**Comment by DavidRoy** [comment]
@kazlauskis please close when implemented in the app

**Comment by JotablancoA** [comment]
In my android device with  iMammalia version 1.0.3(2) lagomorph (unknown
species) was not changed with "Rabbits and hares". So this issue should be
open.
Cheers

**Comment by kazlauskis** [comment]
@JotablancoA I have fixed this now in the app. If you provided me the silhouettes then I could add these as well.
