### ISSUE TITLE
Translations terms, common  name species on the web

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#33]
There are some sections in the web that has no been translated. Although we have an excel with the main translations, other parts and drop-down menus that are in the web were not translated. Please could you send us a complete list of  all the term to be translated?.
Would it be possible to translate the names of the variables in the tables?
Could you include the common names of the species in your language?

**Comment by DavidRoy** [comment]
@johnvanbreda - can you advise on:
1. options for translating Indicia table elements
2. linking common names (set in Indicia taxon list) to Drupal language option
3. options for handling translations via Transifex, i.e. export .po from Drupal, translating within Transifex and re-importing .po into Drupal.  The Drupal-Transifex module not be a reliable option?

**Comment by johnvanbreda** [comment]
1. By table elements, do you mean data in tables? If so, then most data which shows text will be terms from termlists that support translation. We might need to do something to make sure any reports pass through the user's selected language as a parameter but at least in principle this should be fine.
2. There is a filter option for limiting common names to the user's chosen language, near the bottom of the Species section of the configuration. 
3. I've had another experiment with the Drupal Transifex module this morning with more success than last time. Shall I install it on the MammalNet dev site to try, and if so, can you email me the API key and link to the Transifex project page please?

**Comment by DavidRoy** [comment]
1. I also meant column headings as well as content
2. I'll investigate
3. I've sent you an API token for iMammalia

**Comment by JotablancoA** [comment]
For the web: The more important issues should be to get that common species names should  appear in local languages. Secondly it will be great if the columns names are in local languages. I dont get to see this info in other languages. I dont get to see or to get to configurate it, even if i am in the Spanish version of the web. 
![imagen](https://user-images.githubusercontent.com/56724741/68679610-7cfa5000-0560-11ea-9978-2dc7a88572f2.png)

**Comment by johnvanbreda** [comment]
Thanks for the API key - can I also have the project URL please @DavidRoy? Also do you have rights to give me developer rights to this repository on GitHub please so I can close issues etc?

**Comment by DavidRoy** [comment]
Project url = www.transifex.com/ceh/imammalia

I've hopefully added you with the necessary rights to the GitHub repository

**Comment by DavidRoy** [comment]
@johnvanbreda what are the three character codes (i.e. equivalents for eng = English) for adding common names for:
German
Croatian
Spanish
Polish

Are these languages configured on the warehouse?

**Comment by johnvanbreda** [comment]
I've just added them to the warehouse (http://warehouse1.indicia.org.uk/index.php/language).
German - deu
Croatian - hrv
Spanish - spa
Polish - pol

**Comment by johnvanbreda** [comment]
I've set up Transifex on the Dev copy of the site for just basic pages. Please can you let me know if my request to translate the Privacy Notice to Spanish has worked?
If this is OK, then I presume you would like Transifex to be used for Indicia pages as well? Indicia can delegate it's translation to Drupal so I hope that by doing this Transifex will be able to pick up the strings.

**Comment by DavidRoy** [comment]
@johnvanbreda.  I'm not sure what to check.
Transifex is showing 0% translation for Spanish for the privacy notice.
however, I notice that the dev site now has a translation module with some some activity:
https://dev-european-mammals.pantheonsite.io/admin/tmgmt/jobs

Also, the privacy notice shows the Spanish translation is in progress
https://dev-european-mammals.pantheonsite.io/node/3/translations

So looking promising?

**Comment by JotablancoA** [comment]
Hi,

Spanish translation is finished

**Comment by johnvanbreda** [comment]
I've followed the steps to request the translation back into Drupal but it seems to be empty. @DavidRoy I've joined Transifex and sent a request to join the team - when you approve that I can see both ends of the system to try and work out what is happening.

**Comment by johnvanbreda** [comment]
@karolis has given me permission to the team. I can see the strings in Transifex but they are flagged as unreviewed. Would it be possible for someone to mark them as reviewed please (as I don't have reviewer permissions).

**Comment by DavidRoy** [comment]
@johnvanbreda I've marked the Spanish translation of the Privacy Notice as reviewed

**Comment by johnvanbreda** [comment]
Thanks @DavidRoy. I've now managed to get the Spanish content to import into Drupal OK on the dev site, after fixing several bugs in the Transifex plugin for Drupal. If we use Transifex for other sites it is likely we'll want to copy these bug fixes across. 

Can you please check that the Dev site is working as you need it to. You can go to Translation -> Sources  to request translations, then when they are completed and reviewed, go to Translation -> Jobs, select Manage for a job, then Check for Updates. Once this is all working I believe it is possible to automate the check for updates on a schedule.

I'm not 100% familiar with how the language menu is set up to work but it's behaviour seemed a bit odd to me. In particular we might need to consider whether the URL alias of each page needs translating in a consistent way as expected by the language setup in Drupal (the Polish privacy notice has one approach, the Spanish another).

**Comment by DavidRoy** [comment]
Thanks, that seems to have worked.
@BirenRathod implemented the approach for the Polish privacy notice and there may been some complication that it was part of the page footer?
I would prefer a consistent approach.

Are we in a position to implement this on live?  I would also like to implement a similar approach for ABLE

**Comment by johnvanbreda** [comment]
Transifex modules now enabled and configured on live. Please test and let me know if there are any problems.

**Comment by DavidRoy** [comment]
I've looked at the functionality.  I did the following:
1. Translation -> Sources.  Requested translation of 'Record details'
2. This appeared as a resource in Transifex as expected.  However, the strings within the Indicia content were not available for translation (e.g. column headings).
3. However, I translated the string 'Record details' into Spanish and marked this translation as 'Reviweed'
4. In Drupal site, then following instructions = Translation -> Jobs, select Manage for a job, then Check for Updates.

This did not result in the expected translation.  See: https://european-mammals.brc.ac.uk/es/node/6?occurrence_id=12552130

that still has text 'Record details' in English.

@johnvanbreda - were these the right steps and please advise

**Comment by johnvanbreda** [comment]
I had to do 2 things:
1) Enable translation using Drupal (instead of the default Indicia built in translation) by setting helper_config::$delegate_translation_to_hostsite=TRUE.
2) Enable the locales source translation management tools submodule, to allow Drupal translation strings to be sent to Transifex (as opposed to whole content items). 

Now you can find the translation strings on the Sources tab if you set Choose source to Locale.

**Comment by DavidRoy** [comment]
Thanks John

@JotablancoA I have pushed some strings for translation to Transifex.  Can you translate to Spanish so we can test if the pages update.

Link in Transifex = https://www.transifex.com/ceh/imammalia/translate/#pl_PL/$/193035906?q=translated%3Ano

Example iMammalia website page where the translations should appear:
https://european-mammals.brc.ac.uk/es/node/6?occurrence_id=12552130

**Comment by JotablancoA** [comment]
I did it

**Comment by DavidRoy** [comment]
@johnvanbreda I'm not sure this is working yet.

I have been testing the translation of the 'Record external key' into Spanish for the record details page.

Transifex is showing the string as recieved, translated and reviewed - as expected
Drupal is showing the translation job to be finished. https://european-mammals.brc.ac.uk/en/admin/tmgmt/jobs?state=5&source_language=All&target_language=es&translator=All

The record details page is still showing the string 'Record external key' in english
https://european-mammals.brc.ac.uk/es/record/detalles?occurrence_id=12552130

Is there a caching issue?

**Comment by johnvanbreda** [comment]
The link should be https://european-mammals.brc.ac.uk/es/record/details?occurrence_id=12552130 which does work.

**Comment by JotablancoA** [comment]
This error may have occurred because some links (or parts of them) were
included in Transifex to be translated. It was not clear to the person who
made the translation whether or not they had to translate those links.

en/records/details  to  es/ registros/ detalles

**Comment by johnvanbreda** [comment]
Yes, that would have happened because the page was identified as English and submitted for translation along with all it's settings. The page is now language unspecified and just the individual strings should get submitted for translation.

**Comment by DavidRoy** [comment]
Closing, suggest we raise new issues for any remaining translation problems
