### ISSUE TITLE
Authomatic change of the language Web

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#34]
Could be possible that the launch web (imammalia), identify the browser configuration of the user, to change automatically to the user language?.

**Comment by DavidRoy** [comment]
This should now be implemented.  Please close if this works for you

**Comment by JotablancoA** [comment]
I dont get it, it does not work. I used three different browsers (about cache issue), and two computers..

**Comment by DavidRoy** [comment]
hmm, this should work out-of-the box with Drupal (https://www.drupal.org/docs/8/multilingual/enable-language-negotiation).  

I've now enable all detection methods.  Sorry to ask you test again, but I can't test this myself

**Comment by JotablancoA** [comment]
I try again, but it doesn't work. I tried even using Inprivate window, and
three different browsers...

**Comment by johnvanbreda** [comment]
@JotablancoA are you referring to automatic detection when you are logged in, or when you are logged out? When you are logged in, the language setting is saved in your profile which overrides the browser configuration.

**Comment by JotablancoA** [comment]
In the home page of the web site. https://european-mammals.brc.ac.uk  you
need to change the language manually to
https://european-mammals.brc.ac.uk/es
It is independent if you are logged or not

**Comment by johnvanbreda** [comment]
Now fixed. I had to do the following:

- Use language negotiation in the following order: URL, Browser, Selected Language
- Turn off other language negotiation methods
- Set the URL configuration so that English maps to /en.
- Turn off the internal page cache module.

Now, paths which don't specify a language in their URL will resort to browser negotiation.
