### ISSUE TITLE
large mustelids?

### ISSUE THREAD

**Issue by mscandura** [BiologicalRecordsCentre/MammalNet-Europe#36]
In the taxonomic list appearing in iMammalia "small mustelid" is present (I suppose weasels and stoats) but "large mustelid" is not. Nor the single species are present. So how to record a marten or a polecat?
Apologies if this issue was already discussed!

**Comment by JotablancoA** [comment]
At the moment Marten or polecat should be recorded as "small mustelids" at less in comparison to badgers and otters...hopefully we should include specific card for these flag species...

**Comment by mscandura** [comment]
Ok... to me, but are users aware of this? In my opinion it is misleading. I would have preferred the term 'other mustelids'

**Comment by DavidRoy** [comment]
@JotablancoA 
Is the requirement here to relabel 'small mustelids' as 'other mustelids'?

**Comment by JotablancoA** [comment]
The term small mustelids can be confusing, Massimo's proposal makes sense to me. Please use 'other mustelids'.  However, because of the flag species character, I would prefer that all mustelids have their own species card. This is one of the main criticisms received by users, Why Mustelids do not have a species card?.  If you review the records received you can see that there are some Mustelids records in iMammalia.

**Comment by kazlauskis** [comment]
I have now renamed the 'Small mustelid' to 'Other mustelid'. Translators should update this in their translations as well.

**Comment by kazlauskis** [comment]
@JotablancoA if the requirement here is to also add new species cards (polecat etc.) then please feel free to create a new ticket as I will close this one once the App is on the apps stores. Cheers!

**Comment by johnvanbreda** [comment]
@kazlauskis what taxa_taxon_lists ID is this taxon? Does it need to be updated on the warehouse as well?

**Comment by kazlauskis** [comment]
I am not sure if this needs changing the common name on the warehouse as it doens't have any at the moment: [440863](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/440863)
