### ISSUE TITLE
Page error attempting to add new taxa

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#38]
When trying to create a new taxa via the warehouse interface.  Aiming to add a new family to a new mammal order created
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/create/258

The page has an error message that prevents saving (see image):
![err wh](https://user-images.githubusercontent.com/2699478/68688567-a377b580-0577-11ea-867a-f6f0c995b7ae.png)

**Comment by johnvanbreda** [comment]
@DavidRoy Can you let me know exactly what field values you were trying to add please?

**Comment by DavidRoy** [comment]
Closing, but will reopen with more details if re-occurs
