### ISSUE TITLE
add ES verification page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#4]
Requires Drupal role = 'Verifier'

No filter required (i.e. all verifiers see everything)

Add ES verification system
www.european-mammals.brc.ac.uk\verify

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
Have set a user as role = 'verifier', but when accessing verification system:
https://european-mammals.brc.ac.uk/verify

Get an error message of 'Elasticsearch query failed' and no records shown in the grid

**Comment by johnvanbreda** [comment]
Should be now fixed - a permissions issue.

**Comment by DavidRoy** [comment]
Thanks, looks good
