### ISSUE TITLE
Not possible to edit, delete your own records in the webapp

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#42]
Hi, 
I will report some issues identified in iMammalia web. I apologize if were previously reported. 
1)	It is not possible to change, edit, or correct gps location. We receive a warning; “ The data could not be saved. Validation errors occurred when this form was submitted to the server. The form configuration may be incorrect as it appears the controls associated with these messages are missing from the form.<ul><li>The spatial reference must be supplied.<br/>&nbsp;&nbsp; (related to attribute [sample:geom])</li></ul>”
When I tried to modify location using the map in webapp, also we received this message;
The position is outside the range of the selected map reference system
2)	It is not possible to delete your own records or change the date
3)	When I try to upload an image from my computer, I get the next message. The data could not be saved. The spatial reference is not recognized. The spatial reference was collected using the map in the app. 
Is seems a problem with the spatial data.
Best

**Comment by johnvanbreda** [comment]
@karolis would you be able to recreate the above issues and let me know exactly what the app is sending to the warehouse please?

**Comment by johnvanbreda** [comment]
Sorry @kazlauskis I just spotted this says it's about the web site, not the app. Ignore me!

**Comment by johnvanbreda** [comment]
Fixed - incorrect spatial reference system was configured on the site.
