### ISSUE TITLE
Reported iMammalia app issues by users

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#43]
We have identify two problems with the app
1) A user that got to download the app, got to be registered in the web, but when she sent any record, the app indicated that the records were uploaded, but no records appear in the web list (checked in their list or by a verifier). She tried to install again the app. But not got to solve the problem (Android device).

2) Other user in Germany, downloaded the app but dont get to go a head from the first page in the app (page with logos), the app gets stuck. She tried in different devices with similar results. I don’t know if is useful this info, but the device was configurate in Spanish but she tried to download the app from Germany (Android).

**Comment by JotablancoA** [comment]
Issue number 1 has been solved by user...

**Comment by DavidRoy** [comment]
for #2, can you find out the make of the android phone and version of android running.

**Comment by JotablancoA** [comment]
I asked but got no answer. In a previous email you said you tried two different devices, having the same problem. So the Android version was probably not the problem

**Comment by JotablancoA** [comment]
a typo "In a previous email she said that he shad tried using two different devices, having the same problem"

**Comment by JotablancoA** [comment]
for number 2  issue was resolved. She reported that when she arrived in Spain at Christmas the application started to work properly... and now in Germany it continues to work.  I don't know if this information can give you a clue about what was going on.
