### ISSUE TITLE
Bat & Seal records (unknown species category)

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#45]
We have received some records from Bats and Seals in iMammalia. Could be possible to create a (Unknown) category for each group?  Bats (unknown species), Seal (unknown species), in similar way as we did with Shrew (unknown speccies). Some user will be more confident to select i Mammalia if they can record these group of species.

**Comment by johnvanbreda** [comment]
@DavidRoy presumably this requires a change to the app to allow the taxa to be used for recording? We already have a taxon called 'bats' in the list, taxa_taxon_list_id 441038, which is a common name for Chiroptera.

We don't have any seals in the European Mammals list though - Pinnipeds are completely missing. Should they be added?

**Comment by DavidRoy** [comment]
@johnvanbreda if you complete the list in Indicia - including 'Pinnipeds'

.... then @kazlauskis can align the list used in the app

**Comment by johnvanbreda** [comment]
@DavidRoy do you have data for a list of European Pinnipeds please?

**Comment by DavidRoy** [comment]
@JotablancoA do you want a complete list of bat names for users to choose, or just an 'uknown bat' option?

**Comment by JotablancoA** [comment]
Hi,
In the application a simple option for bats (unknown) and seals (unknown)
might be fine, but on the website it might be great, that users or
verifiers could edit the records and indicate theright name of the species.

Best,

**Comment by DavidRoy** [comment]
@JotablancoA - that's fine.  Can someone supply us with a list of bat and seal species for Europe.

**Comment by DavidRoy** [comment]
@johnvanbreda 
Can you extend the species list to include any on this European list.

[EMMA2 Full Species List.xlsx](https://github.com/BiologicalRecordsCentre/MammalNet-Europe/files/4180798/EMMA2.Full.Species.List.xlsx)

**Comment by kazlauskis** [comment]
In terms of size, adding two new groups to the app would be a small task.

**Comment by johnvanbreda** [comment]
@DavidRoy I'm sorting out the list data but it's quite a task as some of the taxa in the spreadsheet are already on the list, or are already on the list but need common names adding, and all need their taxonomic hierarchy filled in. 

One question - in the list at the moment, there is a taxon:
accepted name: Ovis ammon OR Ovis gmelini musimon
common name: European mouflon

In the spreadsheet we have a taxon to add:
accepted name: Ovis ammon
common name: Mouflon

According to most sources I can find on the web (Wikipedia, CITES and a few others), the common name for Ovis ammon is actually the Argali, Asian Wild Sheep or Marco Polo Sheep. The mouflon is Ovis Gmelinii musimon.

So, there seems to be a mistake in the common name given for Ovis ammon but I'd like to confirm that with you. Also is the intention to have the name "Ovis ammon OR Ovis gmelini musimon" as a kind of recording aggregate?

**Comment by DavidRoy** [comment]
Thanks John.  i agree that creating the lists properly is quite complex.  Thanks for working through this.

@JotablancoA to advise on the names issue with Ovis...

**Comment by JotablancoA** [comment]
There is not consensus with this species name. Mainly because there are a lot hybridizations and because there are different taxonomic approaches.
In addition could be possible to consider different groups for  corcega, chipre, ceredeña-

This are the different options:
Ovis aries musimon
Ovis orientalis musimon
Ovis gmelini musimon
Ovis musimon

Probably the most accepted is:
Ovis orientalis musimon

However note that in this case in Chipre there is a other subspecie:  Ovis orientalis ophion

**Comment by DavidRoy** [comment]
@JotablancoA 
So, can confirm the action we take on this.  My understanding is:
We include in the list:
taxon: Ovis orientalis musimon [preferred name]
common name: European Mouflon

Do you also want the other names included as synonyms of O. orientalis musimon and for these available for recorders to select within the website if editing records?

**Comment by JotablancoA** [comment]
Please see the response  from Massimo Scandura, he has more knowledge about
this issue than me. Please follow his recomendation

this is a topic that I have been dealing with during the preparation of the
last checklist of the Italian mammals (
http://www.italian-journal-of-mammalogy.it/Mammals-of-Italy-an-annotated-checklist,111473,0,2.html
Mammals of Italy: an annotated checklist
<http://www.italian-journal-of-mammalogy.it/Mammals-of-Italy-an-annotated-checklist,111473,0,2.html>
Checklists represent a basic tool for conservation and management of
regional faunas. However, our knowledge on species composition in a
territory changes over time due to species movements across borders,
extinctions, introductions, as well as to new taxonomic evidence. We aimed
to provide the...
www.italian-journal-of-mammalogy.it
)

The taxonomy of the mouflon has a long and complex history and is still
debated.

The currently accepted classification is either Ovis gmelini musimon or
Ovis aries musimon, depending on whether the lineage arose before or after
the sheep domestication. Phylogenetic studies (even recently) produced
contrasting results, and this support the present confusion.

The last clear position by the IUCN caprine specialist group puts the
mouflon in Ovis aries. This is the reason why it is not present in the IUCN
redlist.

Ovis ammon is wrong as this is the name of Argali.

The Urial, ancestor of the sheep, is now Ovis gmelini at the meeting of
2016 in Cyprus, where the 5th International Symposium on Mouflon and a
meeting of the IUCN speicalist group took place (I have the document in
case you want to have a look) and the former name Ovis orientalis was
declared synonimus of Ovis gmelini. The Cyprus mouflon was renamed as O.
gmelini ophion, because it was accepted that it arose before domestication.
The European muflon instead is still unclear.

To complicate stuffs somebody proposed Ovis musimon (but they are
splitters... also proposing the Sardinian wild deer as Cervus corsicanus).

Unfortunately important sources like the IUCN redlist or the Habitat
Directive are not updated, so people tend to use old or wrong taxonomy. For
instance iNaturalis/GBIF still use an old taxonomy


Now, iMammalia users/verifiers may not be aware of taxonomical issues and
our aim is just that species are correctly recorded.

*So, I suggest to use a single name, i.e. Ovis gmelini musimon (already in
use), and mention O. aries musimon and O. orientalis musimon as alias but
only in the species card (preventing  confusion).*

Best

Massimo

**Comment by DavidRoy** [comment]
@JotablancoA thanks for this very comprehensive answer
@johnvanbreda can you please implement the following:
taxon: Ovis gmelini musimon [preferred name]
common name: European Mouflon

synonyms:
O. aries musimon
O. orientalis musimon

**Comment by johnvanbreda** [comment]
Import now done - presumably the original request now requires changes in the app?

**Comment by kazlauskis** [comment]
Hi all, I just want to double-check that the requirement here is to add two new (Bat & Seal) unknown species categories in the app, is that right? 

Warehouse ids:

**Bats** `taxa_taxon_list_id` =  441038
**Seals** `taxa_taxon_list_id` = 461469 (Phocidae)

**Comment by DavidRoy** [comment]
Yes.  The issue got a bit sidetracked, but the original requirement was to add bats (unknown) and seals (unknown) as options

**Comment by kazlauskis** [comment]
Cool, and Seals = Phocidae?

**Comment by DavidRoy** [comment]
yes
