### ISSUE TITLE
Linking iMammalia app with MammalNet species filter

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#47]
Do you think it would be appropriate to incorporate the MammalNet link inside the iMammalia app? 
https://mammalnet.com/filters/
This way users with an internet connection could explore additional information about more species. This would avoid overloading the apps with too many images as species. 
For example, some users asked to incorporate information about tracks and signals on the web. Perhaps incorporating that information on the web is easier than inside the app. 
Best, 
Jose A Blanco

**Comment by kazlauskis** [comment]
Yes, this would be quick to add external links to species profiles.

**Comment by kazlauskis** [comment]
Hi @JotablancoA I have added the links to all existing species now. This will take the user to the Mammalnet website species profiles. Could you please check if this looks good to you? 

This only covers existing species. To add this to any of the missing mammals it will need another ticket created as this would be a much bigger task. Cheers! 

<img width="325" alt="Screenshot 2020-04-02 at 08 10 09" src="https://user-images.githubusercontent.com/7383162/78220505-93765900-74b9-11ea-93c5-1857f72b35cd.png">
<img width="1272" alt="Screenshot 2020-04-02 at 08 10 16" src="https://user-images.githubusercontent.com/7383162/78220507-940eef80-74b9-11ea-8c4c-a56328396e50.png">

**Comment by JotablancoA** [comment]
Thanks,
What do you think if we change "profile" to "online profile" or "web
profile"?...maybe it'll make it clear that you need to be connected to the
Internet

**Comment by kazlauskis** [comment]
Sure, I will rename it to `web profile` then.
