### ISSUE TITLE
gps issue in the app

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#51]
Joaquin reported that his automatic tracking does not work. If he tries to use the location icon inside the map, but he can't get activate the GPS properly. 
The GPS icon in the smartphone is active and works correctly with Google map

**Comment by kazlauskis** [comment]
This requires more information, like phone make, operating system, app version etc. Has given enough permissions to the app to use the GPS?

**Comment by kazlauskis** [comment]
This wasn't reported by anyone else. I am closing this for now.
