### ISSUE TITLE
Submission date not correct on record details view

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#52]
Potentially relates to ES Index update issue?

Example, recordId = https://european-mammals.brc.ac.uk/en/record/details?occurrence_id=12816852

But issue also present for most recent records, e.g .https://european-mammals.brc.ac.uk/en/record/details?occurrence_id=12835680

Submission date
Entered on 1 and last updated on 1

Data in warehouse view is correct.

Example screenshots
![im1](https://user-images.githubusercontent.com/2699478/75116885-a6993c00-5664-11ea-9974-794a6449b93f.jpg)
![im2](https://user-images.githubusercontent.com/2699478/75116886-a731d280-5664-11ea-9dc9-c5b5be5d0e23.png)

**Comment by johnvanbreda** [comment]
Fixed. Related to using Drupal translation.
