### ISSUE TITLE
problem editing species name in website

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#55]
When we try to change any Mustelidae record to Martes foina. It appears as "Beech marten, Stone marten, Martes foina". But in the table the variable "species" has the scientific name empty , 
It seems as if this species scientific name was not available. 
I send you a screenshot

![imagen](https://user-images.githubusercontent.com/56724741/75986374-3dc88400-5eee-11ea-99af-022e7eb7a3a1.png)

**Comment by johnvanbreda** [comment]
This is now fixed.
