### ISSUE TITLE
Additional field in the app for wild boar

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#56]
add the following fields (_only for wild boar_): 
gender, 
age (piglet/juvenile/adult), 
state of decomposition (fresh carcass/decomposed/dry (just bones left))

method (addition of 'hunted')

**Comment by kazlauskis** [comment]
Are these new attributes I should create or should I reuse some existing ones? I can't remember if the website has any recording forms I should look into.

**Comment by kazlauskis** [comment]
@GrahamCSmith I have added the new attributes to the app now and it is available within the web demo, could you please check that it looks all good to you? Use your normal account credentials there.
https://imammalia.herokuapp.com/demo.html 

Few other notes:
* This will need some new interface translations, how should we let our translators know?
* Also, at the moment, I have the 'Hunted' method available for all the species, should I restrict it to boar only?
* I feel the type and the decomposition fields are somewhat similar and overlapping but it might be OK.

**Comment by GrahamCSmith** [comment]
The new fields seem to be just what was asked for. I'm happy if we leave hunter for all species. If the new fields are in Transifex I'll make sure the other translators deal with these asap.

**Comment by JotablancoA** [comment]
Regarding to the improvement in iMammalia app, in relation to life stage variables. 
@GrahamCSmith @DavidRoy 
Wouldn't it be better to keep the categories, age, sex, decomposition in all species?
Only, that for the rest of the species the age could be juvenile/ adult
Piglet is used for wild boar...
