### ISSUE TITLE
add Serbia and Macedonia as country options in app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#57]
In support of wild boar recording

**Comment by kazlauskis** [comment]
Where could I get the country species lists?

**Comment by DavidRoy** [comment]
@GrahamCSmith can you supply the lists for new countries for the iMammalia app

**Comment by GrahamCSmith** [comment]
Will do - I'll sort these out tomorrow.

**Comment by GrahamCSmith** [comment]
Here is the updated species list for Serbia and North Macedonia. I've taken the species.csv file and all added details are in red. I've also added the European souslik and description in case we can add this one as well.

**Comment by GrahamCSmith** [comment]
Don't seem to have access to upload a file, so I'll email it to you both.

**Comment by kazlauskis** [comment]
@GrahamCSmith I understand the new European Souslik shares the same habitats, photo and mammalnet website profile as the Spotted souslik. Let me know if isn't the case.

**Comment by GrahamCSmith** [comment]
I believe so,

**Comment by kazlauskis** [comment]
Great, thanks. Alpine marmot doesn't have a value in the Serbian column, I assume it isn't present there.

**Comment by kazlauskis** [comment]
Are we adding the Serbian and Macedonian languages as well?

**Comment by DavidRoy** [comment]
Yes, setup in transifex and translators invited

**Comment by GrahamCSmith** [comment]
Correct - no Alpine marmot in Serbia to my knowledge

**Comment by kazlauskis** [comment]
Which of the Macedonian languages are we adding? 😄
https://en.wikipedia.org/wiki/Languages_of_North_Macedonia

**Comment by GrahamCSmith** [comment]
I believe we are adding Cyrillic Macedonian.

**Comment by kazlauskis** [comment]
Sorry, yes, it was all set up and ready on Transifex like David said.

**Comment by kazlauskis** [comment]
Having European and Spotted sousliks with the same picture next to each other looks a bit strange to my eye. Any chance of getting a different photo? 

<img width="324" alt="Screenshot 2020-04-02 at 13 11 37" src="https://user-images.githubusercontent.com/7383162/78247866-88382300-74e3-11ea-9fb2-ae55ed13bc8b.png">

**Comment by GrahamCSmith** [comment]
European souslik picture in Wikipedia seems Ok to use: https://commons.wikimedia.org/wiki/File:Europ%C3%A4ischer_Ziesel_in_Hockstellung.jpg

**Comment by mammalnet** [comment]
![Tekunica foto](https://user-images.githubusercontent.com/56908715/79004233-9f66b880-7b54-11ea-8129-be055cdd49d7.jpg)
Here you go a photo of European souslik from the Special Nature Reserve Kraljevac in Serbia.
By the way the currently used common name of European souslik is European ground squirrel.
Also, who is doing Serbian translation since I'm Serbian?

**Comment by DavidRoy** [comment]
re: Also, who is doing Serbian translation since I'm Serbian?

The extension of the app to Macedonia and Serbia is through the FAO.
@JotablancoA can advise on the translations.  Transifex allows multiple translators and review

**Comment by JotablancoA** [comment]
@DavidRoy,  Yesterday I responded directly to @KarolinaPetrovic in relation to this issue . I dont know who is the responsible for  this translation from FAO. I think they are working on it. If it is requested we can ask. 
Karolina eye is welcomed to review or improve this translation. She already has access to iMammalia in transifex.

**Comment by DavidRoy** [comment]
The person translating is Milan Pandurovic who is a collaborator with FAO.  He has completed the translation for Serbian

**Comment by GrahamCSmith** [comment]
Just to note that the 'About' section probably needs updating as it only mentions the 4 pilot countries. We should add North Macedonia and Serbia to the list. Also, do we need to update the  'Credits' ?

**Comment by kazlauskis** [comment]
@GrahamCSmith sure, if you could send me the updated texts then I will incorporate those.

**Comment by GrahamCSmith** [comment]
I would suggest the following changes to the "About" section, as this minimises current and future translations:

Paragraph 1 sentence 2: It is set up to easily record mammals in pilot countries: Spain, Germany, Poland, Croatia, North Macedonia and Serbia. 

Paragraph 3 sentence 2: It holds a species list for Spain, Germany, Poland, Croatia, North Macedonia and Serbia but does not limit.....

**Comment by kazlauskis** [comment]
Thanks, I'll update this and leave it to translators to change their texts as well then.

**Comment by mammalnet** [comment]
Hi, I have made changes in Transifex and added Serbia and Macedonia. Please update everything, so I can take a final look. Also, please remove my name from the list of Credits for Serbian and Macedonian versions. Thanks!
