### ISSUE TITLE
Mapping Serbia and Kosovo

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#58]
Just a reminder that on the web site the countries listed include Serbia (but this map includes Kosovo), and it does not include Bosnia and Herzegovina. Is it possible to correct Serbia, and add Kosovo and Bosnia before the revised app goes live.

**Comment by GrahamCSmith** [comment]
@DavidRoy can we fix this mapping issue?

**Comment by DavidRoy** [comment]
@GrahamCSmith what we'd need to do for this is have the new boundaries and to integrate with the EU Nuts regions that we currently use (https://ec.europa.eu/eurostat/web/regions-and-cities/overview).

I suggest we do the following:
1. keep the existing NUTs boundary for 'Serbia'.  Could you suggest a name for this
2. add in separate boundaries for 'Serbia' and 'Kosova'. Again can you suggest names for these in the drop-down lists
3. add in a Bosnia and Herzegovina boundary that is current missing from NUTS

Does that seem reasonable?

Note for me: to implement, good advice via https://gis.stackexchange.com/questions/177741/seeking-free-shapefile-of-european-countries

**Comment by GrahamCSmith** [comment]
@DavidRoy I'm told the latest EEA data in includes Kosovo: 
https://www.eea.europa.eu/data-and-maps/data/eea-mapdata-and-templates-gis-6
but we can't get to the files. I don't know if there is an update for your link?
If not then (noting all the names listed are in English) we can change the existing boundary to 'Serbia and Kosovo' and add the others.

**Comment by DavidRoy** [comment]
@johnvanbreda can you pick this issue up, thanks

**Comment by johnvanbreda** [comment]
I've changed the existing Serbia location name to Serbia and Kosovo. 

The child NUTS 1 boundaries within the Serbia boundary (now Serbia and Kosovo) only cover Serbia, so I can union them to create a Serbia only boundary. I can also substract this from the total boundary to create a Kosovo boundary. But, that will leave us with a Kosovo boundary that doesn't have any NUTS regions within it. Same problem if we add Bosnia Herzegovina (which I need to source the boundary for). Is it OK for the system to not have the NUTS regions within a country boundary? 

Also, if Serbia and Kosovo are recognised as separate entities, is keeping the original unioned boundary muddling things? Would it be better to rename it back to Serbia but change it's boundary to exclude Kosovo, then add Kosovo separately?

**Comment by DavidRoy** [comment]
I can't completely get my head around this, but in answer to your questions.
1. It is ok not having NUTS regions within a country boundary in this case
2. @GrahamCSmith to advise on the question of boundary combinations!

**Comment by GrahamCSmith** [comment]
@johnvanbreda I note that a recent record in Kosovo does not appear when we select Serbia, so best to rename the current "Serbia and Kosovo" to "Serbia" when you redefine the boundary to exclude Kosovo. Then if you can add Kosovo, and Bosnia. No problems with no NUTS regions within them.

**Comment by johnvanbreda** [comment]
Here's the SQL script I've written which split Serbia & Kosovo into 2 separate countries on the Countries 2016 list:
```
-- We have an existing location, Serbia and Kosovo (ID 216136). 
-- This has NUTS level 1 children only covering Serbia. 
-- We want to separate the boundaries into Serbia + Kosovo rather than combine them.

-- Steps
-- Added a dummy location using warehouse UI - Test Serbia, id 249205.
-- Added a dummy location using warehouse UI - Test Kosovo, id 249206.
-- Updated Test Serbia to have the boundary of the sum of all Serbia & Kosovo's children, since this excludes Kosovo.
update locations set boundary_geom=(select st_union(boundary_geom) from locations where parent_id=216136) where id=249205;
-- Made the Test Kosovo boundary the difference of 216136 and 249205
update locations set boundary_geom=st_difference((select boundary_geom from locations where id=216136), (select boundary_geom from locations where id=249205)) where id=249206;
-- Due to differences in boundary precisions, this resulted in a slither of polygons around the edge of Serbia that were left included in Test Kosovo. 
-- Remove these errors by changing Test Kosovo's boundary to only include it's largest polygon:
update locations set boundary_geom=(
select (st_dump(boundary_geom)).geom from locations 
where id=249206
order by st_area((st_dump(boundary_geom)).geom) desc limit 1) where id=249206;
-- Now we can change Serbia and Kosovo back to being just Serbia.
update locations set name='Serbia', updated_on=now(), boundary_geom=(select boundary_geom from locations where id=249205) where id=216136;
-- Add Kosovo to the list of countries.
update locations set name='Kosovo', code='XK', updated_on=now(), location_type_id=16516 where id=249206;

-- Now ensure Elasticsearch index lookup tables correct.
-- See https://github.com/Indicia-Team/support_files/commit/a018aaeb0ab2ef67395103fae787ee5078ee15b0.
-- Restart Logstash.

-- Clean up
update locations set deleted=true where id=249205;

-- Finally queue for re-indexing.
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_spatial_index_builder_location', 'location', id, 100, 2, now()
from locations where id in (216136, 249206);
```

**Comment by johnvanbreda** [comment]
Bosnia & Herzegovina now included in the list of available countries. It turns out the boundary was already present but I'd limited the list to countries with NUTS children.
