### ISSUE TITLE
Enhanced GBIF data publishing

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#59]
following #5 

Suggested enhancements:
1. Include link to associated images
2. Include occurrence attributes - e.g. if they are animals observed, dead on the road or tracks and signs (Observation Method or observation type) 
3. Include location accuracy field.  Current all set to 50 but more information is captured via the App.  In iMammalia there are two field with the same name (Location accuracy) one with free text and other with a dropdown menu.  Potentially include multiple accuracy value - GPS fix, sample_attribute information

**Comment by johnvanbreda** [comment]
I've started work on a custom Dwc extraction for the MammalNet data. A couple of questions:

1. If I use https://dwc.tdwg.org/list/#dwc_associatedMedia to extract photos, does it matter that we are providing URLs without separate licence information? (This may be a wider issue if we do the same for iRecord?)
2. For the location accuracy data we need to map the values to numbers, so I've mapped the drop down terms to the highest possible value (50-100m becomes 50 etc). For >1km I've set it to an arbitrary 5000. Does that sound OK to you?

**Comment by johnvanbreda** [comment]
Also @DavidRoy do you have a feeling for which DwC term to map the observation type attribute to? See https://dwc.tdwg.org/list/.

**Comment by DavidRoy** [comment]
dwc_basisOfRecord?

In response to other questions.
1. @JotablancoA @GrahamCSmith do you have a view on image licences.  We don't allow users to set a licence but do we think a default CC-BY is appropriate?
2. @JotablancoA @GrahamCSmith to advise

**Comment by GrahamCSmith** [comment]
1 @DavidRoy @johnvanbreda CC-BY is fine for me.
2 @DavidRoy @johnvanbreda I would mark it at the approximate mid-point (5m, 25m, 50m, 500m), and for >1km at 2km. This will stop the data being used at a higher resolution as most people will extract data to use below a set threshold (e.g. 10m, 1km).

**Comment by johnvanbreda** [comment]
1. My issues with licences was relating to the fact that associatedMedia is just a list of URLs with no explicit licence for each media element. I'm not sure if I'm missing something but it looks like the licence only applies to the occurrence level. Should I set a licence CC-BY on the record then? Should we include that info on the site terms & conditions?
2. I've changed to the mid-points + 2km.

**Comment by johnvanbreda** [comment]
I've set the Dwc licence field to CC BY as a default, with any specified record-level licence code overriding this, though there are unlikely to be record level licences in this dataset.

@DavidRoy I've prepped a DwC extraction in the IPT and it is ready for publishing at http://ipt.brc.ac.uk/ipt/manage/resource.do?r=mammalnet if you are happy with the above.

**Comment by JotablancoA** [comment]
Thanks @johnvanbreda 

CC BY is fine for us. I don't know if @GrahamCSmith will have a different opinion. 
@DavidRoy Finally, was it possible to incorporate some of the proposals to improve the information to be shared with GBIF?

Suggested enhancements:
 
1.  Include link to associated images
2.  Include occurrence attributes - e.g. if they are animals observed, dead on the road or tracks and signs (Observation Method or observation type)
3. Include location accuracy field. Current all set to 50 but more information is captured via the App. In iMammalia there are two field with the same name (Location accuracy) one with free text and other with a dropdown menu. Potentially include multiple accuracy value - GPS fix, sample_attribute information

**Comment by GrahamCSmith** [comment]
CC BY is fine by me @JotablancoA @johnvanbreda

**Comment by DavidRoy** [comment]
@JotablancoA.  I think we've dealt with most of the requirements.
1. Include link to associated images = **_approach agreed_**
2. Include occurrence attributes - e.g. if they are animals observed, dead on the road or tracks and signs (Observation Method or observation type)
= we need to agree which DwC term to map the observation type attribute to? See https://dwc.tdwg.org/list/ @JotablancoA and @GrahamCSmith to decide
3. Include location accuracy field. Current all set to 50 but more information is captured via the App. In iMammalia there are two field with the same name (Location accuracy) one with free text and other with a dropdown menu. Potentially include multiple accuracy value - GPS fix, sample_attribute information = _**approach agreed**_

@johnvanbreda in the interim, can you please publish the update at http://ipt.brc.ac.uk/ipt/manage/resource.do?r=mammalnet

**Comment by johnvanbreda** [comment]
Here's the updated dataset: https://www.gbif.org/dataset/3ccfe992-043a-4fff-951d-1e6e158854da.
1. Link to associated images is done.
2. ObservationType - I've mapped to a dynamicProperty field, because it doesn't directly map to anything else.
3. Coordinate uncertainty in metres is now populated, as provided by the app.
