### ISSUE TITLE
Species name not appearing on ES-all records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#6]
Species name is not appearing on 
https://european-mammals.brc.ac.uk/explore/all-records

Warehouse view shows name being submitted by app and stored.

Is this related to ES indexing of the Euro Mammals species list?

**Comment by johnvanbreda** [comment]
Fixed. You were correct - ES indexing needs a lookup table of species data which only covered UKSI + EBMS data, so I added the MammalNet list as well.

**Comment by DavidRoy** [comment]
Thanks, now resolved so closing
