### ISSUE TITLE
countries are lacking in the country menu list

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#61]
Do you know why in iMammalia website, when you explore records,
several countries are lacking in the country menu list? but they are
present in the menu list when you enter verification and filter records
by country.

For instance Bosnia-Herzegovina, but also Russia, Belarus, Ukraine and
possibly others. Is it just an oversight?

Message from: Massimo

**Comment by JotablancoA** [comment]
Also for Kosovo
 However on the issue of Kosovo, this might cause political tension. If you make a separate Kosovo area, it would be recommended that you apply a disclaimer (*Asterix) stating:
“” As per United Nations Security Council resolution 1244””

**Comment by johnvanbreda** [comment]
I've added Russia(n Federation), Belarus and Ukraine. Kosovo has an * with a tooltip if you hover over it.

**Comment by johnvanbreda** [comment]
Now done, with disclaimer message shown when Kosovo selected.
