### ISSUE TITLE
Privacy Notice links broken ??

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#62]
Although there are available pages for privacy note in the iMammalia website in some cases is broken the link (at least for my an others). 
https://european-mammals.brc.ac.uk/en/privacy-
https://european-mammals.brc.ac.uk/pl/privacy-notice
https://european-mammals.brc.ac.uk/es/node/3
https://european-mammals.brc.ac.uk/hr/node/3
Note that url is different in other language versions

From the app ( my profile is associated to spanish version) i dont get access to the privacy note (page-not-found warning) , to change the language in the privacy note page, does not solve the problem. 
In similar way, from the web, i dont get access to the privacy notice. 
I get access to the link only if i initiate the web using the polish version, an then click on Policy Notice link from:
https://european-mammals.brc.ac.uk/pl  (footnote section)

Once I have access to the Polish version of "Policy Notice" then if I change the language of the web page it allows me to see the other language versions... EN ES HR GE
I don't understand why this happens. 
Could it be solved?

Best

**Comment by DavidRoy** [comment]
@johnvanbreda can you fix this one please.  Also, note that the privacy-notice page has linked to Transifex for translation
https://www.transifex.com/ceh/imammalia/txdrupal_3_node/

**Comment by johnvanbreda** [comment]
@DavidRoy Isn't this problem because the "ref links" block has only English and Polish translations, therefore the other languages show the English block with incorrect links which change your language? Also the Privacy Notice page itself needs other translations added.

**Comment by DavidRoy** [comment]
@johnvanbreda I'm not sure what 'ref links' block refers to, but you are right that some translated pages are missing.  We will send these to Transifex for translation then revisit this issue

**Comment by johnvanbreda** [comment]
The block at the bottom of the page, containing the copyright notice and privacy notice link is known as the Ref Links block. However I think that the Privacy Notice link should actually be handled as a menu item rather than part of a bigger custom block so I've changed it - the menu is called Footer.

**Comment by johnvanbreda** [comment]
Closing as all the links now work - some pages still need translating though.
