### ISSUE TITLE
Website to display all fields

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#63]
@DavidRoy Is it possible to get the wild boar field Type (i.e. Dead - roadkill and Dead - other) to be displayed on "explore all records". This is required by FAO to track carcasses.

**Comment by DavidRoy** [comment]
@johnvanbreda can you add this field to the explore reports.  I should have said, this is the current priority issue

**Comment by johnvanbreda** [comment]
Done
