### ISSUE TITLE
Squirrel (unknown)

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#65]
A number of records are appearing as squirrel (unknown), but this is not an option within the App.
14731372; 14219779
Both records from different countries arrived as above and have not been redetermined. There are a total of 15 such records, and in the pilot countries there is only the red squirrel S vulgaris. Barbary ground squirrel is in the App but only occurs in the Canaries, where we have no records.

**Comment by johnvanbreda** [comment]
Is it just a case of the app using a different term for Sciuridae. @kazlauskis the ID of squirrel (unknown) is 14731372, what does the app have associated with this ID?

**Comment by kazlauskis** [comment]
Hi, the taxon id we use in the app is `440914`. Is that not correct?

**Comment by johnvanbreda** [comment]
Sorry, cut and paste error. 441296 is Squirrel (unknown), but this is linked as the common name for Sciuridae (440914). So the app is fine - the record is being submitted as Sciuridae and the common name is showing as Squirrel (unknown). 

@GrahamCSmith is this OK from your perspective?

**Comment by GrahamCSmith** [comment]
@johnvanbreda Not sure I follow this. We have 618 records of red squirrel. One grey squirrel (not in the app) and one Barbary ground squirrel (in the App). The former was re-determined, and the latter seen in Morocco. All other records in Europe should be of the red squirrel. So why are we getting 618 red squirrels, and 15 squirrel unknown? These should all show as Sciurus vulgaris - red squirrel.

**Comment by GrahamCSmith** [comment]
@johnvanbreda @kazlauskis It appears that these records are often unknown species of rodents. Is it possible that small rodent, mouse, other mustelid or rat (unknown) is being recorded as Squirrel (unknown)?

**Comment by kazlauskis** [comment]
The 15 `Squirrel (unknown)` are actually `small rodent` records.

Like you know the app itself doesn't have the `Squirrel (unknown)` option but it has the `small rodent` choice. The `small rodent` is mapped to the *Sciuridae*  and in the warehouse the common name for *Sciuridae* is `Squirrel (unknown)`. So when the user sends the  `small rodent` from the app it is shown as `Squirrel (unknown)` in the website.  It makes sense to keep the same common name for *Sciuridae* in the app and the website. If you confirmed whether it should be `Squirrel (unknown)` or `Small rodent` then I will either change it in the warehouse or the app.

For reference, the mentioned groups are currently attached to these warehouse ids:
* small rodent: 440914 (taxon Sciuridae)
* mouse: 440935 (taxon Muridae)
* other mustelid: 440863 (taxon Mustelidae)
* rat (unknown): 440938 (taxon Rattus)

**Comment by GrahamCSmith** [comment]
@DavidRoy @kazlauskis The small rodent group should be mapped to Rodentia (Order rather than Family). Although most will be sub-order Myomorpha, some records could be squiridae. Not sure what code Rodentia is. Can all current Squirrel unknown records then be changed to Rodentia.

**Comment by johnvanbreda** [comment]
Rodentia is 440905. 

@DavidRoy shall I run an update query to change all records from 440914 to 440905 for MammalNet, then update the caches and ES index?

**Comment by DavidRoy** [comment]
@johnvanbreda yes please
@kazlauskis can you update the ID in the app

This bug obviously crept in somewhere along the line and good for @GrahamCSmith to identify the issue

**Comment by kazlauskis** [comment]
OK, I will update the app with the new id for the `small rodent`. The app uses a data sheet that is currently shared with Jose and it would be great if someone could to double check the species values it contains. @GrahamCSmith would you be able to do it if I shared the document with you as well?

**Comment by GrahamCSmith** [comment]
@kazlauskis Yes I should be able to check this.

**Comment by JotablancoA** [comment]
> 
> 
> OK, I will update the app with the new id for the `small rodent`. The app uses a data sheet that is currently shared with Jose and it would be great if someone could to double check the species values it contains. @GrahamCSmith would you be able to do it if I shared the document with you as well?

This issue was reported some moths ago. Some urban mice (unknown) reported as squirrel. And i think it was solved, but probably in last update rise again.

**Comment by johnvanbreda** [comment]
I've updated the existing data so the old Sciuridae records will now be Rodentia. Here's a script just in case it's needed again:
```sql
drop table if exists to_fix;
select id 
into temporary to_fix
from occurrences
where taxa_taxon_list_id=440914 and website_id=122

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from to_fix;

update occurrences set taxa_taxon_list_id=440905 where id in (select id from to_fix);
```
