### ISSUE TITLE
Updating the Eastern hedgehog

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#68]
In the App the Eastern hedgehog is called Erinaceus concolor. Recent genetic studies have split the eastern hedgehog into two. E concolor (white-breasted hedgehog) is restricted to Turkey and outside our countries for the app. The revised Eastern hedgehog is now Erinaceus roumanicus. This will need to be changed in the App on the next update. No need to change the description or map. Once this is done, we can manually change the records on the web site if needed as there are only 16 so far. But we will also need to update GBIF after all this!

**Comment by johnvanbreda** [comment]
@DavidRoy I think this is what is required:
Existing E. concolor is renamed to E. concolor sensu lato.
Add new taxon E. concolor sensu stricto
Add new taxon E. roumanicus.

Shall I do that on the warehouse?

**Comment by DavidRoy** [comment]
@johnvanbreda yes please

**Comment by johnvanbreda** [comment]
Should I also add the common names? If so what is the best approach for the old "Eastern Hedgehog" which is attached to E. concolor sensu lato? Just mark it as not for data entry? Or do we need to add something to the name so it is clear it is the "sensu lato" version?

**Comment by johnvanbreda** [comment]
One thing - E. roumanicus seems to be more commonly referred to as the Northern White-Breasted Hedgehog than Eastern Hedgehog. Would that be a better common name to assign?

**Comment by GrahamCSmith** [comment]
@johnvanbreda That's fine with me

**Comment by DavidRoy** [comment]
I defer to Graham on such matters!

**Comment by johnvanbreda** [comment]
That's done. I left the old Eastern Hedgehog name as it was since we are now using Northern White-Breasted Hedgehog for E. roumanicus but let me know if that needs changing.
Also I still need to make this change in the Elasticsearch data but I'll do that once other taxonomic changes are completed.
