### ISSUE TITLE
simplification of ES explore all-records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#7]
Simplifications to: https://european-mammals.brc.ac.uk/explore/all-records

Remove the following columns from the default view:
- Species Group (superfluous as they are all mammals)
- Vice County (as this is a European project)
- Determiner (not needed)

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
Thanks, closing
