### ISSUE TITLE
update photos

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#74]
Replace selected generic species photos.

![2-New-Phocidae_Seals2](https://user-images.githubusercontent.com/7383162/111168582-1c3ab780-859a-11eb-9bc4-18a5aa4f0c53.png)
![2-New_SmallRodents_copia](https://user-images.githubusercontent.com/7383162/111168595-1f35a800-859a-11eb-9358-2228622c2195.png)
![2-New-Mole2](https://user-images.githubusercontent.com/7383162/111168602-20ff6b80-859a-11eb-929e-fbe712bb908c.png)
![2-New-Lagomorpha_Rabbit_Hares](https://user-images.githubusercontent.com/7383162/111168614-23fa5c00-859a-11eb-8928-fc86da1dbb6f.png)

**Comment by kazlauskis** [comment]
@GrahamCSmith which remaining species photos do you mean?

**Comment by GrahamCSmith** [comment]
@kazlauskis the images for Southern White-breasted hedgehog, Apennine hare, Little souslik, Muskrat, Marbled polecat, and Chinese water deer are not yet in the demo.

**Comment by kazlauskis** [comment]
Thanks, I see what you mean. We've done this one already just haven't pushed it to the demo app yet. I am updating it right now so you should be able to see those species pics in the demo any time now.
