### ISSUE TITLE
Update Welcome web page and transfer text to Transifex.

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#76]
@johnvanbreda @kazlauskis 
The current web home page refers to a beta app in four countries. This needs to be updated for version 2.0. The first full paragraph now needs to read:

The iMammalia App is designed to encourage recording of wild mammals. The mobile application is set up to easily record mammals in all European countries. Sightings can be recorded for any mammal, although for the smaller mammals these are reported as generic (e.g. small rodent). Additional comments describing the sighting are very welcome to confirm the species. 

The remaining paragraphs can stay unchanged, but the above text needs to be put into Transifex very soon to ensure this is translated before the end of March.

**Comment by kazlauskis** [comment]
@GrahamCSmith this is just on the website, not the app, is that right?

**Comment by GrahamCSmith** [comment]
@kazlauskis Yes the app text was updated in Transifex. This is just the web text on the Home Page, but will need to be translated.

**Comment by GrahamCSmith** [comment]
@kazlauskis The regard to the 'about' text in the app. This text should now also be placed onto the Play Store / App Store, as these still refer to a pilot study in four countries. I presume that these stores will accept the transifex text for each language?

**Comment by kazlauskis** [comment]
Sure, I will update the texts on the app stores.

**Comment by kazlauskis** [comment]
I have updated the Google Play store with all the languages - I had to remove some words off the Short Description field (max 80 characters allowed) for some languages so translators should review those are still OK.

For the Apple App Store listing, it is in English only at the moment which I have now updated. Making a change to the description requires a new app release which I am pushing now. We can add the translations to the description with the next releases.

Please close the ticket if the above is OK.
