### ISSUE TITLE
Add new species to the warehouse

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/MammalNet-Europe#77]
These species should be added to the [mammals species list ](https://warehouse1.indicia.org.uk/index.php/taxon_list/edit/258) in the warehouse. @johnvanbreda you have added the original list, will you be able to add these new species again now? Otherwise, I can add these myself if there is some way to import the whole list.

Red-necked   wallaby | Macropus rufogriseus | Macropodiformes | Macropodidae
-- | -- | -- | --
Long-eared   hedgehog | Hemiechinus   auritus | Ericnaceomorpha | Erinaceidae
Eastern cottontail rabbit | Sylvilagus floridanus | Lagomorpha | Leporidae
Cape hare | Lepus capensis | Lagomorpha | Leporidae
Apennine hare | Lepus corsicanus | Lagomorpha | Leporidae
Persian   squirrel | Sciurus   anomalus | Rodentia | Sciuridae
Grey squirrel | Sciurus carolinensis | Rodentia | Sciuridae
Calabrian   black squirrel | Sciurus   meridionalis | Rodentia | Sciuridae
Pallas’s squirrel | Callosciurus erythraeus | Rodentia | Sciuridae
Thailand tree squirrel | Callosciurus finlaysonii | Rodentia | Sciuridae
Little souslik | Spermophilus pygmaeus | Rodentia | Sciuridae
Bobak marmot | Marmota bobak | Rodentia | Sciuridae
Russian flying squirrel | Pteromys volans | Rodentia | Sciuridae
Siberian chipmunk | Eutamias sibiricus | Rodentia | Sciuridae
American beaver | Castor canadensis | Rodentia | Castoridae
Crested   porcupine | Hystrix   cristata | Rodentia | Hystricidae
Polar bear | Ursus maritimus | Carnivora | Ursidae
Arctic   fox | Vulpes lagopus | Carnivora | Canidae
Stoat | Mustela erminea | Carnivora | Mustelidae
Steppe   polecat | Mustela   eversmanii | Carnivora | Mustelidae
European mink | Mustela lutreola | Carnivora | Mustelidae
Weasel | Mustela   nivalis | Carnivora | Mustelidae
Western polecat | Mustela putorius | Carnivora | Mustelidae
American mink | Neovison vison | Carnivora | Mustelidae
Beech marten, Stone marten | Martes foina | Carnivora | Mustelidae
Pine   marten | Martes   martes | Carnivora | Mustelidae
Marbled polecat | Vormela peregusna | Carnivora | Mustelidae
Wolverine | Gulo gulo | Carnivora | Mustelidae
Wild goat | Capra aegagrus | Artiodactyla | Bovidae
Musk ox | Ovibos moschatus | Artiodactyla | Bovidae
Reindeer | Rangifer tarandus | Artiodactyla | Cervidae
Reeves’   muntjac | Muntiacus   reevesi | Artiodactyla | Cervidae
Chinese water deer | Hydropotes inermis | Artiodactyla | Cervidae
Southern white-breasted hedgehog | Erinaceus concolor | Ericnaceomorpha | Erinaceidae
Muskrat | Ondatra zibethicus | Rodentia | Cricetidae

**Comment by johnvanbreda** [comment]
I've done that @kazlauskis

**Comment by kazlauskis** [comment]
Thanks! Is there some way I can download the IDs assigned to the new species for submission?

**Comment by johnvanbreda** [comment]
File attached - but do you have a report for pulling species names and IDs from a list?

[data-1617958492202.txt](https://github.com/BiologicalRecordsCentre/MammalNet-Europe/files/6284437/data-1617958492202.txt)

**Comment by kazlauskis** [comment]
Cheers 👍 

I have now written a script that uses `/index.php/services/data/taxa_search` to transform species names to IDs and looks like this works across websites and species lists so I should be OK.
