### ISSUE TITLE
correct species names when transfering data from app

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#79]
@johnvanbreda Currently in the app the **new** species, Southern White-breasted hedgehog (E concolor) submits a record as E concolor. However, the old Eastern hedgehog is now named the Northern white-breasted hedgehog (E roumanicus), but submits a record as "E concolor sensu lato". This should be changed to E roumanicus.
@DavidRoy @kazlauskis Once the renaming of the northern hedgehog is complete, I will need to change the old records of "E concolor" to "E roumanicus". Is this easiest if I do this manually ? - there are only 20 or so. And will this update and correct when we resubmit to GBIF ?

Graham

**Comment by johnvanbreda** [comment]
@DavidRoy I'm not sure if you want me to take a look at the taxonomy issue raised above?

**Comment by DavidRoy** [comment]
yes please

**Comment by johnvanbreda** [comment]
Here's a list of all the Erinaceus names, their IDs, preferred name status and count of records:
```
ID	Preferred name				Name						Preferred		Records
538037	"Erinaceus concolor"			"Erinaceus concolor"				true			3
538038	"Erinaceus concolor"			"Southern white-breasted hedgehog"		false			0
440887	"Erinaceus concolor sensu lato"		"Erinaceus concolor sensu lato"			true			47
440888	"Erinaceus concolor sensu lato"		"Eastern hedgehog"				false			0
473411	"Erinaceus concolor sensu stricto"	"Erinaceus concolor sensu stricto"		true			0
473412	"Erinaceus concolor sensu stricto"	"White-breasted Hedgehog"			false			0
440889	"Erinaceus europaeus"			"Erinaceus europaeus"				true			213
440890	"Erinaceus europaeus"			"Western hedgehog"				false			2
473413	"Erinaceus roumanicus"			"Erinaceus roumanicus"				true			0
473414	"Erinaceus roumanicus"			"Northern White-breasted Hedgehog"		false			0
```

From what you have said, I think @kazlauskis needs to ensure that the species available and IDs used in the app need to match the above. Once this is done, we can either manually change the records, or I can write a query that changes occurrences with taxa_taxon_list_id 440887 to ID 473413. 

Are we certain that all the records currently allocated to Erinaceus concolor sensu lato should really be Erinaceus roumanicus? I would like to check as the counts are different to Graham's expectations.

**Comment by GrahamCSmith** [comment]
John,
The eastern hedgehog has now been divided into a southern and northern species - although people are still arguing where the line is between them!

In essence we need three species in the app.

440889  "Erinaceus europaeus"                 "Erinaceus europaeus"                            true                   213
This is the western hedgehog present in the Uk and elsewhere in western Europe and Scandinavia. No change should be necessary to this. The 2 records of 440890 should be changed to this.


473413  "Erinaceus roumanicus"                "Erinaceus roumanicus"                           true                   0
This is the Northern White-breasted hedgehog which occurs in eastern Europe (eastern Germany, Austria and the Balkans). Every current occurrence of 440887 should be amended to this.


538037  "Erinaceus concolor"                  "Erinaceus concolor"                             true                   3
This is the old name for the eastern hedgehog and was used in the first launch of the app. This is now the Southern white-breasted hedgehog and occurs in non-European Turkey. There are some that refer to hedgehogs in Greece as the southern species, so I can't be certain of where the divide is, but I doubt we have a single confirmed record of this, so the current records should be changed to 'roumanicus'

There is a generic 'hedgehog' in the app which should be reported as 'Erinaceus' genus. If we can confirm the coding used in the app maps to this, then can you change 440887 to 473413, and I'll manually check the others.

Graham

**Comment by kazlauskis** [comment]
@GrahamCSmith this is what we currently have in the app (from shared excel sheet):

```
Western hedgehog (Erinaceus europaeus) = 440889
Northern white-breasted hedgehog (Erinaceus roumanicus) = 440887
Southern white-breasted hedgehog (Erinaceus concolor) = 538037

Hedgehog (Erinaceidae) = 440882
```

As far as I understand the only change I should make in the app is changing the `440887` to `473413` for _Erinaceus roumanicus_ is that correct?

**Comment by GrahamCSmith** [comment]
@kazlauskis . Yes that looks right. I've updated the spreadsheet so it will point to the correct web location as well, and we have a number of other minor changes in Transifex (some still ongoing), so no rush to push an app update.

**Comment by kazlauskis** [comment]
Thanks, it is probably better to fix the IDs now so that John doesn't have to manually change the species data multiple times. I have now updated the app (inc. translations and other datasheet changes) and pushed it for an app store review. The new app update will be v1.2.3 and it should come out within 7 days.

**Comment by GrahamCSmith** [comment]
@kazlauskis Thanks. Will this include Montengrin (Serbian) as the language is complete?

**Comment by kazlauskis** [comment]
No, I have only updated translations of the current languages.

**Comment by GrahamCSmith** [comment]
@kazlauskis - thanks for clarifying.

**Comment by johnvanbreda** [comment]
I've updated 538037 and 440887  to point to roumanicus (473413).

I didn't change Western Hedgehog to point to Erinaceus europaeus since the data model already infers this via the link to the preferred name.

Finally I can confirm that the app's generic Hedgehog ID is correct: Hedgehog (Erinaceidae) = 440882.

**Comment by GrahamCSmith** [comment]
@johnvanbreda This seems to be working OK now. Can we close this one?
