### ISSUE TITLE
add record_details page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#8]
Currently there is a link to record_details for an occurrence from the explore_report (https://european-mammals.brc.ac.uk/explore/all-records) but this currently doesn't have a target page, e.g. 
https://european-mammals.brc.ac.uk/record-details?occurrence_id=11896952

**Comment by johnvanbreda** [comment]
Done. It may need some styling at some point.

**Comment by DavidRoy** [comment]
Thanks, closing
