### ISSUE TITLE
Add Portuguese and Serbian (Montenegrin)

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#82]
@kazlauskis to confirm that both Portuguese and Serbian (Montenegrin) translations are complete. Please also add "Uliana de Castro" and "João P.V. Santos" to the credit list.

**Comment by kazlauskis** [comment]
Thanks, I will pull in the two new languages and will update the credits.

**Comment by GrahamCSmith** [comment]
please also add George Mitsainas to the credit list.

**Comment by GrahamCSmith** [comment]
@kazlauskis Can you please let me know when Portuguese is available on the demo version.

**Comment by kazlauskis** [comment]
Ok, I will work on this this week.

**Comment by kazlauskis** [comment]
@GrahamCSmith we have updated the translations and added Portuguese (Montenegrin was already there in the demo). Also, updated the credits.

This is now available in the app demo page.

**Comment by GrahamCSmith** [comment]
@kazlauskis The Portuguese have made some amendments to the text in Transifex. Can you update the demo please?

**Comment by kazlauskis** [comment]
I have updated the app demo with the latest Portuguese now.

**Comment by GrahamCSmith** [comment]
@kazlauskis All the text has now been agreed for both countries, and I've updated the spreadsheet for species. It is now OK to update the app with Portuguese and Montenegrin. Can you please let me know when this will happen.
Cheers

**Comment by kazlauskis** [comment]
Sure, I'll update the app this week then and will let you know when the Beta release is ready for testing

**Comment by kazlauskis** [comment]
The Beta is approved and available. New testers can use the same links as before:
**iOS**: https://testflight.apple.com/join/Yp9BTBVR
**Android**: https://play.google.com/apps/testing/uk.ac.ceh.imammalia

Let me know when the testing is done and I'll release it to the public.
