### ISSUE TITLE
The record be found.

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [BiologicalRecordsCentre/MammalNet-Europe#89]
The issue was raised here https://irecord.org.uk/forum/mobile-applications/access-my-imammalia-data

Email "You have new notifications" hyperlink redirecting to https://irecord.org.uk website where the record is "not found". Record only exists on the https://european-mammals.brc.ac.uk/ page.

**Comment by GrahamCSmith** [comment]
I have this problem as I submit on Mammal Mapper and iMammalia and get one email update where the link does not connect to the iMammalia web page. This does need to be sorted fairly urgently

**Comment by johnvanbreda** [comment]
I've added configuration for the record details page for website ID 122 to the notification_emails/config/notification_emails.php file so this should now link to the correct website.
