### ISSUE TITLE
out of date species listing

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#90]
@kazlauskis There are two species names in Transifex that are think have been updated: Eastern hedgehog (to northern site-breasted hedgehog) and Corsican hare (to Apennine hare). If these are not being used, is it possible to delete these in Transifex (English) to avoid people trying to translate these out of date terms?

**Comment by kazlauskis** [comment]
@GrahamCSmith sure, we'll remove these two species from Transifex. 

It can be tricky doing a Transifex two-way sync with the current app content so we typically just add new missing terms when the app text changes - do let us know when terms like these aren't relevant anymore and we'll remove these.
