### ISSUE TITLE
Add an option to delete user account in the app

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/MammalNet-Europe#92]
Same as BiologicalRecordsCentre/ABLE#471

- [x] app
- [x] website

**Comment by kazlauskis** [comment]
@andrewvanbreda, would you be able to do the same for the https://european-mammals.brc.ac.uk site?

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis
Yes can do that, but I will need Pantheon access to the project.

Hi @JimBacon
Is that something you are able to sort out please? or could you let me know who is best to contact to get that done (I assume Biren is still away).
Thanks

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,
Welcome back.
Would you be able to set me up with https://european-mammals.brc.ac.uk/ Pantheon Dashboard access whenever you get a chance please.
Thanks
Andy

**Comment by BirenRathod** [comment]
Thanks @andrewvanbreda.

Your account has been added to https://european-mammals.brc.ac.uk/ Pantheon Dashboard.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, I have checked and I will need to update the easy_login module on this site.

I have created accounts on the following 2 sites, could you make me an administrator for them when you get a sec. Cheers.
https://test-brc-europe-mammals.pantheonsite.io/
https://european-mammals.brc.ac.uk/

**Comment by BirenRathod** [comment]
@andrewvanbreda that's done for you. 
@andrewvanbreda Just to let you know that version of iform is bit old, so if you find something missing, you might need to update that. I'm not asking you to do that but if it is possible for you to do, please do it or let me know.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I didn't intend to update iForm as that would be beyond the scope of the anonimsation budget am working with.
The problem with that is also the need to do some testing afterwards (on a site I am unfamiliar with).
Also would need to know I am not overwriting any customisations.

I think just limit my update to the easy_login module only.

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis @BirenRathod 

The site is running the anonymiser now, although am waiting for the test result I setup to see that it is working (this runs as a medium priority scheduled task so there can be a delay).

@BirenRathod I noticed the easy_login update went live when you were doing some updates. That is ok, but when I enabled the Admin Only Account Cancel module I got this message. Just be aware that happened, I do not know the implications of it.

Thanks for installing SMTP Authentication Support
Server settings on SMTP Authentication Support
And there was the think given in case you need to access it.
https://european-mammals.brc.ac.uk/en/admin/config/system/smtp

**Comment by BirenRathod** [comment]
@andrewvanbreda That is fine. Thanks for letting me know.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
Have just checked the result and the anonymiser does seem to have worked on the account I deleted.
Note I am not a contributor to this project, so you will need to close this issue when you are ready.

**Comment by kazlauskis** [comment]
Thanks 🎉
