### ISSUE TITLE
Abundance Category does not give options

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [BiologicalRecordsCentre/MammalNet-Europe#94]
Hi,

I have noticed that "Abundance Category" does not give options.

<img width="1130" alt="Screenshot 2022-11-07 at 14 45 01" src="https://user-images.githubusercontent.com/53124253/200313716-966afeb6-429f-47b5-9216-51074e3c3fc7.png">

**Comment by GrahamCSmith** [comment]
I'm not sure where this is in the app.
